<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="DinkToPdf" Version="1.0.8" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.7" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0-preview.6.25358.103">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.5.25277.114" />

	  <PackageReference Include="Select.Pdf.NetCore" Version="25.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TimeFlick.Application\TimeFlick.Application.csproj" />
  </ItemGroup>

</Project>
